### PR TITLE
Refering Fedora Accounts Instead of Pagure Accounts

### PR DESCRIPTION
**Pull request by brngylni**
Account URL is now updated to refer to Fedora Accounts of authors of tickets and comments. 

Related Issue: #25

### CODE REVIEW

**Comment by onuralpszr** [comment]
@brngylni  please remove the timeout part out from this PR and let's only focus first part using "acc.fpo" instead of pagure.io situations

**Comment by brngylni** [comment]
> @brngylni please remove the timeout part out from this PR and let's only focus first part using "acc.fpo" instead of pagure.io situations

Guess it's ok now.

**Comment by gridhead** [comment]
@brngylni Could you please fix the testcases?

**Comment by brngylni** [comment]
resim
I'm unsure if the part I changed relates to the test case issues. When I try to run the same command, it successfully migrates the repository as you can see in the command. Could it be something subtle I may be missing? Any help would be appreciated

> @brngylni Could you please fix the testcases?

**Comment by gridhead** [comment]
@brngylni Please run `tox` locally in your Python environment and you should be able to see where the tests are failing.

**Comment by brngylni** [comment]
> @brngylni Please run `tox` locally in your Python environment and you should be able to see where the tests are failing.

Yes, I'm trying to do that but even with the current main branch of the repository, tests don't succeed on my end. Even though the exporter exports all branches and successfully migrates them, a lot of tests fail. 


When I try to run the tox on the current main branch with py311
resim



Meanwhile the repository


Source:
resim


Destination:

resim



So I know it may not sound reasonable but, is it possible that there's another thing?

**Comment by gridhead** [comment]
@onuralpszr could you please look into this?

**Comment by gridhead** [comment]
@brngylni please fix the testcases

**Comment by brngylni** [comment]
> > @brngylni Please run `tox` locally in your Python environment and you should be able to see where the tests are failing.
> 
> Yes, I'm trying to do that but even with the current main branch of the repository, tests don't succeed on my end. Even though the exporter exports all branches and successfully migrates them, a lot of tests fail. 
> 
> 
> When I try to run the tox on the current main branch with py311
> resim
> 
> 
> 
> Meanwhile the repository
> 
> 
> Source:
> resim
> 
> 
> Destination:
> 
> resim
> 
> 
> Additionally, I see a test (Migrating repository contents with specifying zero valid branch names) exits with exit code 2 which means that it's partially moved. But when I check, all the branches are migrated.
> 
> So I know it may not sound reasonable but, is it possible that there's another thing? 
> 

@gridhead could you please help about this? Any hint would be appreciated

**Comment by gridhead** [comment]
@brngylni, any references to users like the following

```
https://pagure.io/user/t0xic0der/
```

Should be changed to the following

```
https://accounts.fedoraproject.org/user/t0xic0der/
```

For the testcases to accommodate such a change, the test cases should expect it too.

Please create your own Pagure API key and GitLab API key to test things out.

**Comment by brngylni** [comment]
> @brngylni, any references to users like the following
> 
> ```
> https://pagure.io/user/t0xic0der/
> ```
> 
> Should be changed to the following
> 
> ```
> https://accounts.fedoraproject.org/user/t0xic0der/
> ```
> 
> For the testcases to accommodate such a change, the test cases should expect it too.
> 
> Please create your own Pagure API key and GitLab API key to test things out.

I actually did exactly this. Let me check the test cases

**Review by gridhead — APPROVED** [review]
I will fix the tests after the merge.

**Pull request merged**
