### PR TITLE
Circumvent the rate limits on the API requests

### LINKED ISSUE #10: Find methods to circumvent GitLab rate limits
The information about the rate limits on GitLab can be found here https://docs.gitlab.com/ee/user/gitlab_com/index.html#gitlabcom-specific-rate-limits. 

Here is where I encountered this issue for the first time.

```
[ BUSY ] Migrating issue ticket with labels #11441 'Merge Fedora Pride on matrix.org with our pride:fp.o room' by 'Robert Wright (ID rwright)'...
         Migrated to https://gitlab.com/gridhead/protop2g-test/-/issues/611 in 1.40 second(s)
[ BUSY ] Reading comment information...
         Found 5 entities in 0.00 second(s)
[ BUSY ] Transferring comment (Entity 1 of 5)...
         Transferred to https://gitlab.com/gridhead/protop2g-test/-/issues/611#note_1578276270 in 1.31 second(s)
[ BUSY ] Transferring comment (Entity 2 of 5)...
         Transferred to https://gitlab.com/gridhead/protop2g-test/-/issues/611#note_1578276285 in 0.75 second(s)
[ BUSY ] Transferring comment (Entity 3 of 5)...
         Transferred to https://gitlab.com/gridhead/protop2g-test/-/issues/611#note_1578276299 in 0.82 second(s)
[ BUSY ] Transferring comment (Entity 4 of 5)...
         Transferred to https://gitlab.com/gridhead/protop2g-test/-/issues/611#note_1578276307 in 0.69 second(s)
[ BUSY ] Transferring comment (Entity 5 of 5)...
         Transferred to https://gitlab.com/gridhead/protop2g-test/-/issues/611#note_1578276315 in 1.01 second(s)
[ BUSY ] Migrating issue ticket with labels #11429 'Create CentOS Matrix rooms on fedoraproject.org server and bridge them to IRC channels ' by 'Neal Gompa (ID ngompa)'...
         Migrated to https://gitlab.com/gridhead/protop2g-test/-/issues/612 in 0.91 second(s)
[ BUSY ] Reading comment information...
         Found 8 entities in 0.00 second(s)
[ BUSY ] Transferring comment (Entity 1 of 8)...
         Transferred to https://gitlab.com/gridhead/protop2g-test/-/issues/612#note_1578276341 in 0.67 second(s)
[ BUSY ] Transferring comment (Entity 2 of 8)...
         Transferred to https://gitlab.com/gridhead/protop2g-test/-/issues/612#note_1578276344 in 0.70 second(s)
[ BUSY ] Transferring comment (Entity 3 of 8)...
         Transferred to https://gitlab.com/gridhead/protop2g-test/-/issues/612#note_1578276360 in 0.73 second(s)
[ BUSY ] Transferring comment (Entity 4 of 8)...
         Transferred to https://gitlab.com/gridhead/protop2g-test/-/issues/612#note_1578276369 in 0.96 second(s)
[ BUSY ] Transferring comment (Entity 5 of 8)...
         Transferred to https://gitlab.com/gridhead/protop2g-test/-/issues/612#note_1578276374 in 0.94 second(s)
[ BUSY ] Transferring comment (Entity 6 of 8)...
         Transferred to https://gitlab.com/gridhead/protop2g-test/-/issues/612#note_1578276391 in 0.68 second(s)
[ BUSY ] Transferring comment (Entity 7 of 8)...
         Transferred to https://gitlab.com/gridhead/protop2g-test/-/issues/612#note_1578276395 in 0.68 second(s)
[ BUSY ] Transferring comment (Entity 8 of 8)...
         Transferred to https://gitlab.com/gridhead/protop2g-test/-/issues/612#note_1578276409 in 0.90 second(s)
[ BUSY ] Migrating issue ticket with labels #11428 'mailing list admin - unable to change delimiter between message and list footer' by 'Petr Spacek (ID pspacek)'...
         Migrated to https://gitlab.com/gridhead/protop2g-test/-/issues/613 in 0.82 second(s)
[ BUSY ] Reading comment information...
         Found 5 entities in 0.00 second(s)
[ BUSY ] Transferring comment (Entity 1 of 5)...
         Transferred to https://gitlab.com/gridhead/protop2g-test/-/issues/613#note_1578276427 in 0.68 second(s)
[ BUSY ] Transferring comment (Entity 2 of 5)...
         Transferred to https://gitlab.com/gridhead/protop2g-test/-/issues/613#note_1578276439 in 0.76 second(s)
[ BUSY ] Transferring comment (Entity 3 of 5)...
         Transferred to https://gitlab.com/gridhead/protop2g-test/-/issues/613#note_1578276455 in 0.75 second(s)
[ BUSY ] Transferring comment (Entity 4 of 5)...
         Transferred to https://gitlab.com/gridhead/protop2g-test/-/issues/613#note_1578276469 in 0.75 second(s)
[ BUSY ] Transferring comment (Entity 4 of 5)...
[ FAIL ] Comment transfer failed!
         Failed due to code '429' and reason 'Too Many Requests' in 0.35 second(s)
```

We should find a way to cool down by providing a mandatory wait time before we end up getting an error from the server-side and the execution errors out.

### PR DESCRIPTION
**Pull request by gridhead**
Circumvent the rate limits on the API requests

Fixes #10, #33 and #60

### CODE REVIEW

**Comment by gridhead** [comment]
@Zlopez and @jwflory, reviews appreciated :)

**Review by samyak-jn — APPROVED** [review]
Hello @gridhead :wave: 

Thanks for working on this. verified most of the files consists of license description renaming which is good; otherwise the callwait functions seems right to me along with a supported testcase, so here's my +1 to this.

**Comment by gridhead** [comment]
Apart from a couple of hiccups in between (reported in #66 and #67), my attempt to transfer issue tickets of all states (irrespective of OPEN or SHUT) along with their comments and states from the `pagure.io/fedora-commops` repository turned out to be successful.

Here are some tickets to confirm the success of such a long-winded transfer https://gitlab.com/gridhead/protop2g-test/-/issues/3609, https://gitlab.com/gridhead/protop2g-test/-/issues/3606, https://gitlab.com/gridhead/protop2g-test/-/issues/3603, https://gitlab.com/gridhead/protop2g-test/-/issues/3600, https://gitlab.com/gridhead/protop2g-test/-/issues/3557, https://gitlab.com/gridhead/protop2g-test/-/issues/3554 and https://gitlab.com/gridhead/protop2g-test/-/issues/3551.

Here's the complete result.

image

Here's where it is shown that the tool takes a pause for 60 seconds after having made 195 requests before continuing on to do some more.

image

**Comment by gridhead** [comment]
Thanks for the review, @samyak-jn!

**Review by Zlopez — APPROVED** [review]

**Pull request merged**
