### PR TITLE
Add testing support using VCR.py

### LINKED ISSUE #42: Use VCR.py for unit tests
It's not great to connect to external services each time the tests run. It would be better to use [VCR](https://vcrpy.readthedocs.io/en/latest/) for that purpose, which creates reusable requests. We already using that in [Anitya](https://github.com/fedora-infra/anitya/blob/master/anitya/tests/base.py#L104), so you can look there for guidance.

### PR DESCRIPTION
**Pull request by gridhead**
Add testing support using VCR.py

Fixes #42

### CODE REVIEW

**Comment by gridhead** [comment]
I used [this](https://github.com/kiwicom/pytest-recording) library to speed things up significantly and use fewer resources when it comes to testing HTTP API requests made to Pagure and GitLab. The documentation/blogpost [here](https://code.kiwi.com/articles/pytest-cassettes-forget-about-mocks-or-live-requests/) was handy in helping me to set up VCR.py.

@Zlopez I could use a review here.

**Comment by gridhead** [comment]
One of the previous [test runs](https://github.com/fedora-infra/pagure-exporter/actions/runs/6944348118/job/18891283534) actually connected to GitLab.com to make testing HTTP API requests and used a lot of networking and computing resources while taking as long 3 minutes and 11 seconds to complete. As external services are used, the reliability of the testcases also depend on the services' health, network conditions etc.

With the use of VCR.py, only those HTTP API requests are conveyed all the way up to GitLab.com that are required to test the functionality of cloning and transferring the repository assets. The responses to the majority of HTTP API requests are emulated in this [test run](https://github.com/fedora-infra/pagure-exporter/actions/runs/6948104926/job/18903481790?pr=78) and that brings down the time to as low as 1 minute and 14 seconds.

That is approximately 61.25% time saved on test runs with significant improvement on the reliability of those!

**Review by samyak-jn — APPROVED** [review]
this looked intimidating when I saw +25,436 −137; but then I checked how smartly you added `@pytest.mark.vcr(filter_headers=["Authorization"])` to the test cases that's why i checked in my review that it should be included in all the test cases!

**Comment by gridhead** [comment]
Thanks for the review, @samyak-jn!

**Pull request merged**
